version: '3'
services:
  frontend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: vue-app
    ports:
      - "8080:80"
    network_mode: "host"

  nginx:
    image: nginx:alpine
    container_name: nginx-app
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend