# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/rodri/Documents/Weapon_detection/ai/utils/EDF/design/gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 480)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.backButton = QtWidgets.QPushButton(self.centralwidget)
        self.backButton.setGeometry(QtCore.QRect(30, 60, 31, 181))
        self.backButton.setObjectName("backButton")
        self.nextButton = QtWidgets.QPushButton(self.centralwidget)
        self.nextButton.setGeometry(QtCore.QRect(310, 60, 31, 181))
        self.nextButton.setObjectName("nextButton")
        self.rejectButton = QtWidgets.QPushButton(self.centralwidget)
        self.rejectButton.setGeometry(QtCore.QRect(60, 210, 121, 31))
        self.rejectButton.setObjectName("rejectButton")
        self.acceptButton = QtWidgets.QPushButton(self.centralwidget)
        self.acceptButton.setGeometry(QtCore.QRect(180, 210, 131, 31))
        self.acceptButton.setObjectName("acceptButton")
        self.pwd_lbl = QtWidgets.QLabel(self.centralwidget)
        self.pwd_lbl.setGeometry(QtCore.QRect(40, 310, 291, 17))
        self.pwd_lbl.setObjectName("pwd_lbl")
        self.card_1 = QtWidgets.QLabel(self.centralwidget)
        self.card_1.setGeometry(QtCore.QRect(380, 60, 201, 141))
        self.card_1.setObjectName("card_1")
        self.card_2 = QtWidgets.QLabel(self.centralwidget)
        self.card_2.setGeometry(QtCore.QRect(380, 210, 211, 151))
        self.card_2.setObjectName("card_2")
        self.in_lbl = QtWidgets.QLabel(self.centralwidget)
        self.in_lbl.setGeometry(QtCore.QRect(40, 350, 111, 17))
        self.in_lbl.setObjectName("in_lbl")
        self.out_lbl = QtWidgets.QLabel(self.centralwidget)
        self.out_lbl.setGeometry(QtCore.QRect(40, 380, 111, 17))
        self.out_lbl.setObjectName("out_lbl")
        self.tmp_lbl = QtWidgets.QLabel(self.centralwidget)
        self.tmp_lbl.setGeometry(QtCore.QRect(40, 410, 111, 17))
        self.tmp_lbl.setObjectName("tmp_lbl")
        self.lineEdit_input = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_input.setGeometry(QtCore.QRect(160, 350, 211, 20))
        self.lineEdit_input.setObjectName("lineEdit_input")
        self.lineEdit_output = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_output.setGeometry(QtCore.QRect(160, 380, 211, 20))
        self.lineEdit_output.setObjectName("lineEdit_output")
        self.lineEdit_check = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_check.setGeometry(QtCore.QRect(160, 410, 211, 20))
        self.lineEdit_check.setObjectName("lineEdit_check")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(380, 410, 61, 21))
        self.pushButton.setObjectName("pushButton")
        self.title_lbl = QtWidgets.QLabel(self.centralwidget)
        self.title_lbl.setGeometry(QtCore.QRect(0, 0, 641, 41))
        self.title_lbl.setObjectName("title_lbl")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.backButton.setText(_translate("MainWindow", "<"))
        self.nextButton.setText(_translate("MainWindow", ">"))
        self.rejectButton.setText(_translate("MainWindow", "Reject"))
        self.acceptButton.setText(_translate("MainWindow", "Accept"))
        self.pwd_lbl.setText(_translate("MainWindow", "Current folder: ../.../../../.../"))
        self.card_1.setText(_translate("MainWindow", "File: ##/#####\n"
"\n"
"Files moved: #####\n"
"\n"
"Files discarted: #####"))
        self.card_2.setText(_translate("MainWindow", "FILES MOVED\n"
"\n"
"\n"
"\n"
"With xml: #####\n"
"\n"
"Without xml: #####"))
        self.in_lbl.setText(_translate("MainWindow", "Input folder:"))
        self.out_lbl.setText(_translate("MainWindow", "Output folder:"))
        self.tmp_lbl.setText(_translate("MainWindow", "Checkpoint file:"))
        self.pushButton.setText(_translate("MainWindow", "Load"))
        self.title_lbl.setText(_translate("MainWindow", "Easy Dataset Filter"))
