# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/rodri/Documents/Weapon_detection/controller/design/design.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton1.setGeometry(QtCore.QRect(30, 20, 100, 50))
        self.pushButton1.setObjectName("pushButton1")
        self.pushButton1_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton1_2.setGeometry(QtCore.QRect(140, 20, 100, 50))
        self.pushButton1_2.setObjectName("pushButton1_2")
        self.pushButton1_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton1_3.setGeometry(QtCore.QRect(250, 20, 100, 50))
        self.pushButton1_3.setObjectName("pushButton1_3")
        self.pushButton1_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton1_4.setGeometry(QtCore.QRect(140, 80, 100, 50))
        self.pushButton1_4.setObjectName("pushButton1_4")
        self.pushButton1_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton1_5.setGeometry(QtCore.QRect(30, 80, 100, 50))
        self.pushButton1_5.setObjectName("pushButton1_5")
        self.pushButton1_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton1_6.setGeometry(QtCore.QRect(250, 80, 100, 50))
        self.pushButton1_6.setObjectName("pushButton1_6")
        self.pushButton1_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton1_7.setGeometry(QtCore.QRect(140, 140, 100, 50))
        self.pushButton1_7.setObjectName("pushButton1_7")
        self.pushButton1_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton1_8.setGeometry(QtCore.QRect(250, 140, 100, 50))
        self.pushButton1_8.setObjectName("pushButton1_8")
        self.pushButton1_9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton1_9.setGeometry(QtCore.QRect(30, 140, 100, 50))
        self.pushButton1_9.setObjectName("pushButton1_9")
        self.pushButton1_10 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton1_10.setGeometry(QtCore.QRect(30, 200, 100, 50))
        self.pushButton1_10.setObjectName("pushButton1_10")
        self.pushButton1_11 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton1_11.setGeometry(QtCore.QRect(140, 200, 100, 50))
        self.pushButton1_11.setObjectName("pushButton1_11")
        self.pushButton1_12 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton1_12.setGeometry(QtCore.QRect(250, 200, 100, 50))
        self.pushButton1_12.setObjectName("pushButton1_12")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(370, 140, 121, 111))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(500, 140, 121, 111))
        self.pushButton_2.setObjectName("pushButton_2")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(370, 20, 251, 111))
        self.lineEdit.setObjectName("lineEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton1.setText(_translate("MainWindow", "1"))
        self.pushButton1_2.setText(_translate("MainWindow", "2"))
        self.pushButton1_3.setText(_translate("MainWindow", "3"))
        self.pushButton1_4.setText(_translate("MainWindow", "5"))
        self.pushButton1_5.setText(_translate("MainWindow", "4"))
        self.pushButton1_6.setText(_translate("MainWindow", "6"))
        self.pushButton1_7.setText(_translate("MainWindow", "8"))
        self.pushButton1_8.setText(_translate("MainWindow", "9"))
        self.pushButton1_9.setText(_translate("MainWindow", "7"))
        self.pushButton1_10.setText(_translate("MainWindow", "Back"))
        self.pushButton1_11.setText(_translate("MainWindow", "0"))
        self.pushButton1_12.setText(_translate("MainWindow", "Enter"))
        self.pushButton.setText(_translate("MainWindow", "Settings"))
        self.pushButton_2.setText(_translate("MainWindow", "Alert"))
